/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.demo.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Direccion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1434652318744255169L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Direccion\",\"namespace\":\"com.example.demo.avro\",\"fields\":[{\"name\":\"tipoVia\",\"type\":\"string\"},{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"numero\",\"type\":\"string\"},{\"name\":\"piso\",\"type\":\"string\"},{\"name\":\"codigoPostal\",\"type\":\"string\"},{\"name\":\"poblacion\",\"type\":\"string\"},{\"name\":\"provincia\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Direccion> ENCODER =
      new BinaryMessageEncoder<Direccion>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Direccion> DECODER =
      new BinaryMessageDecoder<Direccion>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Direccion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Direccion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Direccion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Direccion>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Direccion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Direccion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Direccion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Direccion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence tipoVia;
   private java.lang.CharSequence nombre;
   private java.lang.CharSequence numero;
   private java.lang.CharSequence piso;
   private java.lang.CharSequence codigoPostal;
   private java.lang.CharSequence poblacion;
   private java.lang.CharSequence provincia;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Direccion() {}

  /**
   * All-args constructor.
   * @param tipoVia The new value for tipoVia
   * @param nombre The new value for nombre
   * @param numero The new value for numero
   * @param piso The new value for piso
   * @param codigoPostal The new value for codigoPostal
   * @param poblacion The new value for poblacion
   * @param provincia The new value for provincia
   */
  public Direccion(java.lang.CharSequence tipoVia, java.lang.CharSequence nombre, java.lang.CharSequence numero, java.lang.CharSequence piso, java.lang.CharSequence codigoPostal, java.lang.CharSequence poblacion, java.lang.CharSequence provincia) {
    this.tipoVia = tipoVia;
    this.nombre = nombre;
    this.numero = numero;
    this.piso = piso;
    this.codigoPostal = codigoPostal;
    this.poblacion = poblacion;
    this.provincia = provincia;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tipoVia;
    case 1: return nombre;
    case 2: return numero;
    case 3: return piso;
    case 4: return codigoPostal;
    case 5: return poblacion;
    case 6: return provincia;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tipoVia = (java.lang.CharSequence)value$; break;
    case 1: nombre = (java.lang.CharSequence)value$; break;
    case 2: numero = (java.lang.CharSequence)value$; break;
    case 3: piso = (java.lang.CharSequence)value$; break;
    case 4: codigoPostal = (java.lang.CharSequence)value$; break;
    case 5: poblacion = (java.lang.CharSequence)value$; break;
    case 6: provincia = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tipoVia' field.
   * @return The value of the 'tipoVia' field.
   */
  public java.lang.CharSequence getTipoVia() {
    return tipoVia;
  }


  /**
   * Sets the value of the 'tipoVia' field.
   * @param value the value to set.
   */
  public void setTipoVia(java.lang.CharSequence value) {
    this.tipoVia = value;
  }

  /**
   * Gets the value of the 'nombre' field.
   * @return The value of the 'nombre' field.
   */
  public java.lang.CharSequence getNombre() {
    return nombre;
  }


  /**
   * Sets the value of the 'nombre' field.
   * @param value the value to set.
   */
  public void setNombre(java.lang.CharSequence value) {
    this.nombre = value;
  }

  /**
   * Gets the value of the 'numero' field.
   * @return The value of the 'numero' field.
   */
  public java.lang.CharSequence getNumero() {
    return numero;
  }


  /**
   * Sets the value of the 'numero' field.
   * @param value the value to set.
   */
  public void setNumero(java.lang.CharSequence value) {
    this.numero = value;
  }

  /**
   * Gets the value of the 'piso' field.
   * @return The value of the 'piso' field.
   */
  public java.lang.CharSequence getPiso() {
    return piso;
  }


  /**
   * Sets the value of the 'piso' field.
   * @param value the value to set.
   */
  public void setPiso(java.lang.CharSequence value) {
    this.piso = value;
  }

  /**
   * Gets the value of the 'codigoPostal' field.
   * @return The value of the 'codigoPostal' field.
   */
  public java.lang.CharSequence getCodigoPostal() {
    return codigoPostal;
  }


  /**
   * Sets the value of the 'codigoPostal' field.
   * @param value the value to set.
   */
  public void setCodigoPostal(java.lang.CharSequence value) {
    this.codigoPostal = value;
  }

  /**
   * Gets the value of the 'poblacion' field.
   * @return The value of the 'poblacion' field.
   */
  public java.lang.CharSequence getPoblacion() {
    return poblacion;
  }


  /**
   * Sets the value of the 'poblacion' field.
   * @param value the value to set.
   */
  public void setPoblacion(java.lang.CharSequence value) {
    this.poblacion = value;
  }

  /**
   * Gets the value of the 'provincia' field.
   * @return The value of the 'provincia' field.
   */
  public java.lang.CharSequence getProvincia() {
    return provincia;
  }


  /**
   * Sets the value of the 'provincia' field.
   * @param value the value to set.
   */
  public void setProvincia(java.lang.CharSequence value) {
    this.provincia = value;
  }

  /**
   * Creates a new Direccion RecordBuilder.
   * @return A new Direccion RecordBuilder
   */
  public static com.example.demo.avro.Direccion.Builder newBuilder() {
    return new com.example.demo.avro.Direccion.Builder();
  }

  /**
   * Creates a new Direccion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Direccion RecordBuilder
   */
  public static com.example.demo.avro.Direccion.Builder newBuilder(com.example.demo.avro.Direccion.Builder other) {
    if (other == null) {
      return new com.example.demo.avro.Direccion.Builder();
    } else {
      return new com.example.demo.avro.Direccion.Builder(other);
    }
  }

  /**
   * Creates a new Direccion RecordBuilder by copying an existing Direccion instance.
   * @param other The existing instance to copy.
   * @return A new Direccion RecordBuilder
   */
  public static com.example.demo.avro.Direccion.Builder newBuilder(com.example.demo.avro.Direccion other) {
    if (other == null) {
      return new com.example.demo.avro.Direccion.Builder();
    } else {
      return new com.example.demo.avro.Direccion.Builder(other);
    }
  }

  /**
   * RecordBuilder for Direccion instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Direccion>
    implements org.apache.avro.data.RecordBuilder<Direccion> {

    private java.lang.CharSequence tipoVia;
    private java.lang.CharSequence nombre;
    private java.lang.CharSequence numero;
    private java.lang.CharSequence piso;
    private java.lang.CharSequence codigoPostal;
    private java.lang.CharSequence poblacion;
    private java.lang.CharSequence provincia;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.demo.avro.Direccion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tipoVia)) {
        this.tipoVia = data().deepCopy(fields()[0].schema(), other.tipoVia);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.numero)) {
        this.numero = data().deepCopy(fields()[2].schema(), other.numero);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.piso)) {
        this.piso = data().deepCopy(fields()[3].schema(), other.piso);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.codigoPostal)) {
        this.codigoPostal = data().deepCopy(fields()[4].schema(), other.codigoPostal);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.poblacion)) {
        this.poblacion = data().deepCopy(fields()[5].schema(), other.poblacion);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.provincia)) {
        this.provincia = data().deepCopy(fields()[6].schema(), other.provincia);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Direccion instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.demo.avro.Direccion other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.tipoVia)) {
        this.tipoVia = data().deepCopy(fields()[0].schema(), other.tipoVia);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numero)) {
        this.numero = data().deepCopy(fields()[2].schema(), other.numero);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.piso)) {
        this.piso = data().deepCopy(fields()[3].schema(), other.piso);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.codigoPostal)) {
        this.codigoPostal = data().deepCopy(fields()[4].schema(), other.codigoPostal);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.poblacion)) {
        this.poblacion = data().deepCopy(fields()[5].schema(), other.poblacion);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.provincia)) {
        this.provincia = data().deepCopy(fields()[6].schema(), other.provincia);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'tipoVia' field.
      * @return The value.
      */
    public java.lang.CharSequence getTipoVia() {
      return tipoVia;
    }


    /**
      * Sets the value of the 'tipoVia' field.
      * @param value The value of 'tipoVia'.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder setTipoVia(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tipoVia = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tipoVia' field has been set.
      * @return True if the 'tipoVia' field has been set, false otherwise.
      */
    public boolean hasTipoVia() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tipoVia' field.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder clearTipoVia() {
      tipoVia = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nombre' field.
      * @return The value.
      */
    public java.lang.CharSequence getNombre() {
      return nombre;
    }


    /**
      * Sets the value of the 'nombre' field.
      * @param value The value of 'nombre'.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder setNombre(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nombre = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nombre' field has been set.
      * @return True if the 'nombre' field has been set, false otherwise.
      */
    public boolean hasNombre() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nombre' field.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder clearNombre() {
      nombre = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'numero' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumero() {
      return numero;
    }


    /**
      * Sets the value of the 'numero' field.
      * @param value The value of 'numero'.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder setNumero(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.numero = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'numero' field has been set.
      * @return True if the 'numero' field has been set, false otherwise.
      */
    public boolean hasNumero() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'numero' field.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder clearNumero() {
      numero = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'piso' field.
      * @return The value.
      */
    public java.lang.CharSequence getPiso() {
      return piso;
    }


    /**
      * Sets the value of the 'piso' field.
      * @param value The value of 'piso'.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder setPiso(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.piso = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'piso' field has been set.
      * @return True if the 'piso' field has been set, false otherwise.
      */
    public boolean hasPiso() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'piso' field.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder clearPiso() {
      piso = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'codigoPostal' field.
      * @return The value.
      */
    public java.lang.CharSequence getCodigoPostal() {
      return codigoPostal;
    }


    /**
      * Sets the value of the 'codigoPostal' field.
      * @param value The value of 'codigoPostal'.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder setCodigoPostal(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.codigoPostal = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'codigoPostal' field has been set.
      * @return True if the 'codigoPostal' field has been set, false otherwise.
      */
    public boolean hasCodigoPostal() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'codigoPostal' field.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder clearCodigoPostal() {
      codigoPostal = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'poblacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getPoblacion() {
      return poblacion;
    }


    /**
      * Sets the value of the 'poblacion' field.
      * @param value The value of 'poblacion'.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder setPoblacion(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.poblacion = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'poblacion' field has been set.
      * @return True if the 'poblacion' field has been set, false otherwise.
      */
    public boolean hasPoblacion() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'poblacion' field.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder clearPoblacion() {
      poblacion = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'provincia' field.
      * @return The value.
      */
    public java.lang.CharSequence getProvincia() {
      return provincia;
    }


    /**
      * Sets the value of the 'provincia' field.
      * @param value The value of 'provincia'.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder setProvincia(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.provincia = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'provincia' field has been set.
      * @return True if the 'provincia' field has been set, false otherwise.
      */
    public boolean hasProvincia() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'provincia' field.
      * @return This builder.
      */
    public com.example.demo.avro.Direccion.Builder clearProvincia() {
      provincia = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Direccion build() {
      try {
        Direccion record = new Direccion();
        record.tipoVia = fieldSetFlags()[0] ? this.tipoVia : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.nombre = fieldSetFlags()[1] ? this.nombre : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.numero = fieldSetFlags()[2] ? this.numero : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.piso = fieldSetFlags()[3] ? this.piso : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.codigoPostal = fieldSetFlags()[4] ? this.codigoPostal : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.poblacion = fieldSetFlags()[5] ? this.poblacion : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.provincia = fieldSetFlags()[6] ? this.provincia : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Direccion>
    WRITER$ = (org.apache.avro.io.DatumWriter<Direccion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Direccion>
    READER$ = (org.apache.avro.io.DatumReader<Direccion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tipoVia);

    out.writeString(this.nombre);

    out.writeString(this.numero);

    out.writeString(this.piso);

    out.writeString(this.codigoPostal);

    out.writeString(this.poblacion);

    out.writeString(this.provincia);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tipoVia = in.readString(this.tipoVia instanceof Utf8 ? (Utf8)this.tipoVia : null);

      this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);

      this.numero = in.readString(this.numero instanceof Utf8 ? (Utf8)this.numero : null);

      this.piso = in.readString(this.piso instanceof Utf8 ? (Utf8)this.piso : null);

      this.codigoPostal = in.readString(this.codigoPostal instanceof Utf8 ? (Utf8)this.codigoPostal : null);

      this.poblacion = in.readString(this.poblacion instanceof Utf8 ? (Utf8)this.poblacion : null);

      this.provincia = in.readString(this.provincia instanceof Utf8 ? (Utf8)this.provincia : null);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tipoVia = in.readString(this.tipoVia instanceof Utf8 ? (Utf8)this.tipoVia : null);
          break;

        case 1:
          this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);
          break;

        case 2:
          this.numero = in.readString(this.numero instanceof Utf8 ? (Utf8)this.numero : null);
          break;

        case 3:
          this.piso = in.readString(this.piso instanceof Utf8 ? (Utf8)this.piso : null);
          break;

        case 4:
          this.codigoPostal = in.readString(this.codigoPostal instanceof Utf8 ? (Utf8)this.codigoPostal : null);
          break;

        case 5:
          this.poblacion = in.readString(this.poblacion instanceof Utf8 ? (Utf8)this.poblacion : null);
          break;

        case 6:
          this.provincia = in.readString(this.provincia instanceof Utf8 ? (Utf8)this.provincia : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










