/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.productor.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class cliente extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1555076767778761240L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"cliente\",\"namespace\":\"com.example.productor.avro\",\"fields\":[{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"apellido\",\"type\":\"string\"},{\"name\":\"nif\",\"type\":\"string\"},{\"name\":\"telefono\",\"type\":\"string\"},{\"name\":\"direccion\",\"type\":{\"type\":\"record\",\"name\":\"direccion\",\"fields\":[{\"name\":\"tipoVia\",\"type\":\"string\"},{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"numero\",\"type\":\"string\"},{\"name\":\"piso\",\"type\":\"string\"},{\"name\":\"codigoPostal\",\"type\":\"string\"},{\"name\":\"poblacion\",\"type\":\"string\"},{\"name\":\"provincia\",\"type\":\"string\"}]}},{\"name\":\"edad\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<cliente> ENCODER =
      new BinaryMessageEncoder<cliente>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<cliente> DECODER =
      new BinaryMessageDecoder<cliente>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<cliente> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<cliente> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<cliente> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<cliente>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this cliente to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a cliente from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a cliente instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static cliente fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence nombre;
   private java.lang.CharSequence apellido;
   private java.lang.CharSequence nif;
   private java.lang.CharSequence telefono;
   private com.example.productor.avro.direccion direccion;
   private long edad;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public cliente() {}

  /**
   * All-args constructor.
   * @param nombre The new value for nombre
   * @param apellido The new value for apellido
   * @param nif The new value for nif
   * @param telefono The new value for telefono
   * @param direccion The new value for direccion
   * @param edad The new value for edad
   */
  public cliente(java.lang.CharSequence nombre, java.lang.CharSequence apellido, java.lang.CharSequence nif, java.lang.CharSequence telefono, com.example.productor.avro.direccion direccion, java.lang.Long edad) {
    this.nombre = nombre;
    this.apellido = apellido;
    this.nif = nif;
    this.telefono = telefono;
    this.direccion = direccion;
    this.edad = edad;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nombre;
    case 1: return apellido;
    case 2: return nif;
    case 3: return telefono;
    case 4: return direccion;
    case 5: return edad;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nombre = (java.lang.CharSequence)value$; break;
    case 1: apellido = (java.lang.CharSequence)value$; break;
    case 2: nif = (java.lang.CharSequence)value$; break;
    case 3: telefono = (java.lang.CharSequence)value$; break;
    case 4: direccion = (com.example.productor.avro.direccion)value$; break;
    case 5: edad = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'nombre' field.
   * @return The value of the 'nombre' field.
   */
  public java.lang.CharSequence getNombre() {
    return nombre;
  }


  /**
   * Sets the value of the 'nombre' field.
   * @param value the value to set.
   */
  public void setNombre(java.lang.CharSequence value) {
    this.nombre = value;
  }

  /**
   * Gets the value of the 'apellido' field.
   * @return The value of the 'apellido' field.
   */
  public java.lang.CharSequence getApellido() {
    return apellido;
  }


  /**
   * Sets the value of the 'apellido' field.
   * @param value the value to set.
   */
  public void setApellido(java.lang.CharSequence value) {
    this.apellido = value;
  }

  /**
   * Gets the value of the 'nif' field.
   * @return The value of the 'nif' field.
   */
  public java.lang.CharSequence getNif() {
    return nif;
  }


  /**
   * Sets the value of the 'nif' field.
   * @param value the value to set.
   */
  public void setNif(java.lang.CharSequence value) {
    this.nif = value;
  }

  /**
   * Gets the value of the 'telefono' field.
   * @return The value of the 'telefono' field.
   */
  public java.lang.CharSequence getTelefono() {
    return telefono;
  }


  /**
   * Sets the value of the 'telefono' field.
   * @param value the value to set.
   */
  public void setTelefono(java.lang.CharSequence value) {
    this.telefono = value;
  }

  /**
   * Gets the value of the 'direccion' field.
   * @return The value of the 'direccion' field.
   */
  public com.example.productor.avro.direccion getDireccion() {
    return direccion;
  }


  /**
   * Sets the value of the 'direccion' field.
   * @param value the value to set.
   */
  public void setDireccion(com.example.productor.avro.direccion value) {
    this.direccion = value;
  }

  /**
   * Gets the value of the 'edad' field.
   * @return The value of the 'edad' field.
   */
  public long getEdad() {
    return edad;
  }


  /**
   * Sets the value of the 'edad' field.
   * @param value the value to set.
   */
  public void setEdad(long value) {
    this.edad = value;
  }

  /**
   * Creates a new cliente RecordBuilder.
   * @return A new cliente RecordBuilder
   */
  public static com.example.productor.avro.cliente.Builder newBuilder() {
    return new com.example.productor.avro.cliente.Builder();
  }

  /**
   * Creates a new cliente RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new cliente RecordBuilder
   */
  public static com.example.productor.avro.cliente.Builder newBuilder(com.example.productor.avro.cliente.Builder other) {
    if (other == null) {
      return new com.example.productor.avro.cliente.Builder();
    } else {
      return new com.example.productor.avro.cliente.Builder(other);
    }
  }

  /**
   * Creates a new cliente RecordBuilder by copying an existing cliente instance.
   * @param other The existing instance to copy.
   * @return A new cliente RecordBuilder
   */
  public static com.example.productor.avro.cliente.Builder newBuilder(com.example.productor.avro.cliente other) {
    if (other == null) {
      return new com.example.productor.avro.cliente.Builder();
    } else {
      return new com.example.productor.avro.cliente.Builder(other);
    }
  }

  /**
   * RecordBuilder for cliente instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<cliente>
    implements org.apache.avro.data.RecordBuilder<cliente> {

    private java.lang.CharSequence nombre;
    private java.lang.CharSequence apellido;
    private java.lang.CharSequence nif;
    private java.lang.CharSequence telefono;
    private com.example.productor.avro.direccion direccion;
    private com.example.productor.avro.direccion.Builder direccionBuilder;
    private long edad;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.productor.avro.cliente.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nombre)) {
        this.nombre = data().deepCopy(fields()[0].schema(), other.nombre);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.apellido)) {
        this.apellido = data().deepCopy(fields()[1].schema(), other.apellido);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.nif)) {
        this.nif = data().deepCopy(fields()[2].schema(), other.nif);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.telefono)) {
        this.telefono = data().deepCopy(fields()[3].schema(), other.telefono);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.direccion)) {
        this.direccion = data().deepCopy(fields()[4].schema(), other.direccion);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasDireccionBuilder()) {
        this.direccionBuilder = com.example.productor.avro.direccion.newBuilder(other.getDireccionBuilder());
      }
      if (isValidValue(fields()[5], other.edad)) {
        this.edad = data().deepCopy(fields()[5].schema(), other.edad);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing cliente instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.productor.avro.cliente other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.nombre)) {
        this.nombre = data().deepCopy(fields()[0].schema(), other.nombre);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.apellido)) {
        this.apellido = data().deepCopy(fields()[1].schema(), other.apellido);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nif)) {
        this.nif = data().deepCopy(fields()[2].schema(), other.nif);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.telefono)) {
        this.telefono = data().deepCopy(fields()[3].schema(), other.telefono);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.direccion)) {
        this.direccion = data().deepCopy(fields()[4].schema(), other.direccion);
        fieldSetFlags()[4] = true;
      }
      this.direccionBuilder = null;
      if (isValidValue(fields()[5], other.edad)) {
        this.edad = data().deepCopy(fields()[5].schema(), other.edad);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'nombre' field.
      * @return The value.
      */
    public java.lang.CharSequence getNombre() {
      return nombre;
    }


    /**
      * Sets the value of the 'nombre' field.
      * @param value The value of 'nombre'.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder setNombre(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.nombre = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'nombre' field has been set.
      * @return True if the 'nombre' field has been set, false otherwise.
      */
    public boolean hasNombre() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'nombre' field.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder clearNombre() {
      nombre = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'apellido' field.
      * @return The value.
      */
    public java.lang.CharSequence getApellido() {
      return apellido;
    }


    /**
      * Sets the value of the 'apellido' field.
      * @param value The value of 'apellido'.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder setApellido(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.apellido = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'apellido' field has been set.
      * @return True if the 'apellido' field has been set, false otherwise.
      */
    public boolean hasApellido() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'apellido' field.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder clearApellido() {
      apellido = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'nif' field.
      * @return The value.
      */
    public java.lang.CharSequence getNif() {
      return nif;
    }


    /**
      * Sets the value of the 'nif' field.
      * @param value The value of 'nif'.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder setNif(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.nif = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'nif' field has been set.
      * @return True if the 'nif' field has been set, false otherwise.
      */
    public boolean hasNif() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'nif' field.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder clearNif() {
      nif = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'telefono' field.
      * @return The value.
      */
    public java.lang.CharSequence getTelefono() {
      return telefono;
    }


    /**
      * Sets the value of the 'telefono' field.
      * @param value The value of 'telefono'.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder setTelefono(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.telefono = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'telefono' field has been set.
      * @return True if the 'telefono' field has been set, false otherwise.
      */
    public boolean hasTelefono() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'telefono' field.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder clearTelefono() {
      telefono = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'direccion' field.
      * @return The value.
      */
    public com.example.productor.avro.direccion getDireccion() {
      return direccion;
    }


    /**
      * Sets the value of the 'direccion' field.
      * @param value The value of 'direccion'.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder setDireccion(com.example.productor.avro.direccion value) {
      validate(fields()[4], value);
      this.direccionBuilder = null;
      this.direccion = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'direccion' field has been set.
      * @return True if the 'direccion' field has been set, false otherwise.
      */
    public boolean hasDireccion() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'direccion' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.productor.avro.direccion.Builder getDireccionBuilder() {
      if (direccionBuilder == null) {
        if (hasDireccion()) {
          setDireccionBuilder(com.example.productor.avro.direccion.newBuilder(direccion));
        } else {
          setDireccionBuilder(com.example.productor.avro.direccion.newBuilder());
        }
      }
      return direccionBuilder;
    }

    /**
     * Sets the Builder instance for the 'direccion' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.productor.avro.cliente.Builder setDireccionBuilder(com.example.productor.avro.direccion.Builder value) {
      clearDireccion();
      direccionBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'direccion' field has an active Builder instance
     * @return True if the 'direccion' field has an active Builder instance
     */
    public boolean hasDireccionBuilder() {
      return direccionBuilder != null;
    }

    /**
      * Clears the value of the 'direccion' field.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder clearDireccion() {
      direccion = null;
      direccionBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'edad' field.
      * @return The value.
      */
    public long getEdad() {
      return edad;
    }


    /**
      * Sets the value of the 'edad' field.
      * @param value The value of 'edad'.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder setEdad(long value) {
      validate(fields()[5], value);
      this.edad = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'edad' field has been set.
      * @return True if the 'edad' field has been set, false otherwise.
      */
    public boolean hasEdad() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'edad' field.
      * @return This builder.
      */
    public com.example.productor.avro.cliente.Builder clearEdad() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public cliente build() {
      try {
        cliente record = new cliente();
        record.nombre = fieldSetFlags()[0] ? this.nombre : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.apellido = fieldSetFlags()[1] ? this.apellido : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.nif = fieldSetFlags()[2] ? this.nif : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.telefono = fieldSetFlags()[3] ? this.telefono : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (direccionBuilder != null) {
          try {
            record.direccion = this.direccionBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("direccion"));
            throw e;
          }
        } else {
          record.direccion = fieldSetFlags()[4] ? this.direccion : (com.example.productor.avro.direccion) defaultValue(fields()[4]);
        }
        record.edad = fieldSetFlags()[5] ? this.edad : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<cliente>
    WRITER$ = (org.apache.avro.io.DatumWriter<cliente>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<cliente>
    READER$ = (org.apache.avro.io.DatumReader<cliente>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.nombre);

    out.writeString(this.apellido);

    out.writeString(this.nif);

    out.writeString(this.telefono);

    this.direccion.customEncode(out);

    out.writeLong(this.edad);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);

      this.apellido = in.readString(this.apellido instanceof Utf8 ? (Utf8)this.apellido : null);

      this.nif = in.readString(this.nif instanceof Utf8 ? (Utf8)this.nif : null);

      this.telefono = in.readString(this.telefono instanceof Utf8 ? (Utf8)this.telefono : null);

      if (this.direccion == null) {
        this.direccion = new com.example.productor.avro.direccion();
      }
      this.direccion.customDecode(in);

      this.edad = in.readLong();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);
          break;

        case 1:
          this.apellido = in.readString(this.apellido instanceof Utf8 ? (Utf8)this.apellido : null);
          break;

        case 2:
          this.nif = in.readString(this.nif instanceof Utf8 ? (Utf8)this.nif : null);
          break;

        case 3:
          this.telefono = in.readString(this.telefono instanceof Utf8 ? (Utf8)this.telefono : null);
          break;

        case 4:
          if (this.direccion == null) {
            this.direccion = new com.example.productor.avro.direccion();
          }
          this.direccion.customDecode(in);
          break;

        case 5:
          this.edad = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










