/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.productor.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class clienteAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5500942693775293626L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"clienteAvro\",\"namespace\":\"com.example.productor.avro\",\"fields\":[{\"name\":\"cliente\",\"type\":{\"type\":\"record\",\"name\":\"cliente\",\"fields\":[{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"apellido\",\"type\":\"string\"},{\"name\":\"nif\",\"type\":\"string\"},{\"name\":\"telefono\",\"type\":\"string\"},{\"name\":\"direccion\",\"type\":{\"type\":\"record\",\"name\":\"direccion\",\"fields\":[{\"name\":\"tipoVia\",\"type\":\"string\"},{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"numero\",\"type\":\"string\"},{\"name\":\"piso\",\"type\":\"string\"},{\"name\":\"codigoPostal\",\"type\":\"string\"},{\"name\":\"poblacion\",\"type\":\"string\"},{\"name\":\"provincia\",\"type\":\"string\"}]}},{\"name\":\"edad\",\"type\":\"long\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<clienteAvro> ENCODER =
      new BinaryMessageEncoder<clienteAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<clienteAvro> DECODER =
      new BinaryMessageDecoder<clienteAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<clienteAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<clienteAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<clienteAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<clienteAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this clienteAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a clienteAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a clienteAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static clienteAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private com.example.productor.avro.cliente cliente;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public clienteAvro() {}

  /**
   * All-args constructor.
   * @param cliente The new value for cliente
   */
  public clienteAvro(com.example.productor.avro.cliente cliente) {
    this.cliente = cliente;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cliente;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cliente = (com.example.productor.avro.cliente)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cliente' field.
   * @return The value of the 'cliente' field.
   */
  public com.example.productor.avro.cliente getCliente() {
    return cliente;
  }


  /**
   * Sets the value of the 'cliente' field.
   * @param value the value to set.
   */
  public void setCliente(com.example.productor.avro.cliente value) {
    this.cliente = value;
  }

  /**
   * Creates a new clienteAvro RecordBuilder.
   * @return A new clienteAvro RecordBuilder
   */
  public static com.example.productor.avro.clienteAvro.Builder newBuilder() {
    return new com.example.productor.avro.clienteAvro.Builder();
  }

  /**
   * Creates a new clienteAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new clienteAvro RecordBuilder
   */
  public static com.example.productor.avro.clienteAvro.Builder newBuilder(com.example.productor.avro.clienteAvro.Builder other) {
    if (other == null) {
      return new com.example.productor.avro.clienteAvro.Builder();
    } else {
      return new com.example.productor.avro.clienteAvro.Builder(other);
    }
  }

  /**
   * Creates a new clienteAvro RecordBuilder by copying an existing clienteAvro instance.
   * @param other The existing instance to copy.
   * @return A new clienteAvro RecordBuilder
   */
  public static com.example.productor.avro.clienteAvro.Builder newBuilder(com.example.productor.avro.clienteAvro other) {
    if (other == null) {
      return new com.example.productor.avro.clienteAvro.Builder();
    } else {
      return new com.example.productor.avro.clienteAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for clienteAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<clienteAvro>
    implements org.apache.avro.data.RecordBuilder<clienteAvro> {

    private com.example.productor.avro.cliente cliente;
    private com.example.productor.avro.cliente.Builder clienteBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.productor.avro.clienteAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cliente)) {
        this.cliente = data().deepCopy(fields()[0].schema(), other.cliente);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasClienteBuilder()) {
        this.clienteBuilder = com.example.productor.avro.cliente.newBuilder(other.getClienteBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing clienteAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.productor.avro.clienteAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.cliente)) {
        this.cliente = data().deepCopy(fields()[0].schema(), other.cliente);
        fieldSetFlags()[0] = true;
      }
      this.clienteBuilder = null;
    }

    /**
      * Gets the value of the 'cliente' field.
      * @return The value.
      */
    public com.example.productor.avro.cliente getCliente() {
      return cliente;
    }


    /**
      * Sets the value of the 'cliente' field.
      * @param value The value of 'cliente'.
      * @return This builder.
      */
    public com.example.productor.avro.clienteAvro.Builder setCliente(com.example.productor.avro.cliente value) {
      validate(fields()[0], value);
      this.clienteBuilder = null;
      this.cliente = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cliente' field has been set.
      * @return True if the 'cliente' field has been set, false otherwise.
      */
    public boolean hasCliente() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'cliente' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.productor.avro.cliente.Builder getClienteBuilder() {
      if (clienteBuilder == null) {
        if (hasCliente()) {
          setClienteBuilder(com.example.productor.avro.cliente.newBuilder(cliente));
        } else {
          setClienteBuilder(com.example.productor.avro.cliente.newBuilder());
        }
      }
      return clienteBuilder;
    }

    /**
     * Sets the Builder instance for the 'cliente' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.productor.avro.clienteAvro.Builder setClienteBuilder(com.example.productor.avro.cliente.Builder value) {
      clearCliente();
      clienteBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'cliente' field has an active Builder instance
     * @return True if the 'cliente' field has an active Builder instance
     */
    public boolean hasClienteBuilder() {
      return clienteBuilder != null;
    }

    /**
      * Clears the value of the 'cliente' field.
      * @return This builder.
      */
    public com.example.productor.avro.clienteAvro.Builder clearCliente() {
      cliente = null;
      clienteBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public clienteAvro build() {
      try {
        clienteAvro record = new clienteAvro();
        if (clienteBuilder != null) {
          try {
            record.cliente = this.clienteBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("cliente"));
            throw e;
          }
        } else {
          record.cliente = fieldSetFlags()[0] ? this.cliente : (com.example.productor.avro.cliente) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<clienteAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<clienteAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<clienteAvro>
    READER$ = (org.apache.avro.io.DatumReader<clienteAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.cliente.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.cliente == null) {
        this.cliente = new com.example.productor.avro.cliente();
      }
      this.cliente.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.cliente == null) {
            this.cliente = new com.example.productor.avro.cliente();
          }
          this.cliente.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










